concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: git config user.name "${GITHUB_ACTOR}"
      - run: git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: echo "${{ secrets.DOTNPMRC }}" > .npmrc
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if pnpm run should-semantic-release ; then
            pnpm release-it --verbose
          fi
name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
